// Generated by gencpp from file dyplom/goalResult.msg
// DO NOT EDIT!


#ifndef DYPLOM_MESSAGE_GOALRESULT_H
#define DYPLOM_MESSAGE_GOALRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dyplom
{
template <class ContainerAllocator>
struct goalResult_
{
  typedef goalResult_<ContainerAllocator> Type;

  goalResult_()
    : status()  {
    }
  goalResult_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::dyplom::goalResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dyplom::goalResult_<ContainerAllocator> const> ConstPtr;

}; // struct goalResult_

typedef ::dyplom::goalResult_<std::allocator<void> > goalResult;

typedef boost::shared_ptr< ::dyplom::goalResult > goalResultPtr;
typedef boost::shared_ptr< ::dyplom::goalResult const> goalResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dyplom::goalResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dyplom::goalResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dyplom::goalResult_<ContainerAllocator1> & lhs, const ::dyplom::goalResult_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dyplom::goalResult_<ContainerAllocator1> & lhs, const ::dyplom::goalResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dyplom

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dyplom::goalResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dyplom::goalResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dyplom::goalResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dyplom::goalResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dyplom::goalResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dyplom::goalResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dyplom::goalResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::dyplom::goalResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::dyplom::goalResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dyplom/goalResult";
  }

  static const char* value(const ::dyplom::goalResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dyplom::goalResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"string status\n"
;
  }

  static const char* value(const ::dyplom::goalResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dyplom::goalResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goalResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dyplom::goalResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dyplom::goalResult_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYPLOM_MESSAGE_GOALRESULT_H
