// Generated by gencpp from file dyplom/problem_gen.msg
// DO NOT EDIT!


#ifndef DYPLOM_MESSAGE_PROBLEM_GEN_H
#define DYPLOM_MESSAGE_PROBLEM_GEN_H

#include <ros/service_traits.h>


#include <dyplom/problem_genRequest.h>
#include <dyplom/problem_genResponse.h>


namespace dyplom
{

struct problem_gen
{

typedef problem_genRequest Request;
typedef problem_genResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct problem_gen
} // namespace dyplom


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dyplom::problem_gen > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::dyplom::problem_gen&) { return value(); }
};

template<>
struct DataType< ::dyplom::problem_gen > {
  static const char* value()
  {
    return "dyplom/problem_gen";
  }

  static const char* value(const ::dyplom::problem_gen&) { return value(); }
};


// service_traits::MD5Sum< ::dyplom::problem_genRequest> should match
// service_traits::MD5Sum< ::dyplom::problem_gen >
template<>
struct MD5Sum< ::dyplom::problem_genRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dyplom::problem_gen >::value();
  }
  static const char* value(const ::dyplom::problem_genRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dyplom::problem_genRequest> should match
// service_traits::DataType< ::dyplom::problem_gen >
template<>
struct DataType< ::dyplom::problem_genRequest>
{
  static const char* value()
  {
    return DataType< ::dyplom::problem_gen >::value();
  }
  static const char* value(const ::dyplom::problem_genRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dyplom::problem_genResponse> should match
// service_traits::MD5Sum< ::dyplom::problem_gen >
template<>
struct MD5Sum< ::dyplom::problem_genResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dyplom::problem_gen >::value();
  }
  static const char* value(const ::dyplom::problem_genResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dyplom::problem_genResponse> should match
// service_traits::DataType< ::dyplom::problem_gen >
template<>
struct DataType< ::dyplom::problem_genResponse>
{
  static const char* value()
  {
    return DataType< ::dyplom::problem_gen >::value();
  }
  static const char* value(const ::dyplom::problem_genResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYPLOM_MESSAGE_PROBLEM_GEN_H
