// Auto-generated. Do not edit!

// (in-package dyplom.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class goalGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.x = null;
      this.y = null;
      this.z = null;
      this.ox = null;
      this.oy = null;
      this.oz = null;
      this.ow = null;
    }
    else {
      if (initObj.hasOwnProperty('x')) {
        this.x = initObj.x
      }
      else {
        this.x = 0.0;
      }
      if (initObj.hasOwnProperty('y')) {
        this.y = initObj.y
      }
      else {
        this.y = 0.0;
      }
      if (initObj.hasOwnProperty('z')) {
        this.z = initObj.z
      }
      else {
        this.z = 0.0;
      }
      if (initObj.hasOwnProperty('ox')) {
        this.ox = initObj.ox
      }
      else {
        this.ox = 0.0;
      }
      if (initObj.hasOwnProperty('oy')) {
        this.oy = initObj.oy
      }
      else {
        this.oy = 0.0;
      }
      if (initObj.hasOwnProperty('oz')) {
        this.oz = initObj.oz
      }
      else {
        this.oz = 0.0;
      }
      if (initObj.hasOwnProperty('ow')) {
        this.ow = initObj.ow
      }
      else {
        this.ow = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type goalGoal
    // Serialize message field [x]
    bufferOffset = _serializer.float64(obj.x, buffer, bufferOffset);
    // Serialize message field [y]
    bufferOffset = _serializer.float64(obj.y, buffer, bufferOffset);
    // Serialize message field [z]
    bufferOffset = _serializer.float64(obj.z, buffer, bufferOffset);
    // Serialize message field [ox]
    bufferOffset = _serializer.float64(obj.ox, buffer, bufferOffset);
    // Serialize message field [oy]
    bufferOffset = _serializer.float64(obj.oy, buffer, bufferOffset);
    // Serialize message field [oz]
    bufferOffset = _serializer.float64(obj.oz, buffer, bufferOffset);
    // Serialize message field [ow]
    bufferOffset = _serializer.float64(obj.ow, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type goalGoal
    let len;
    let data = new goalGoal(null);
    // Deserialize message field [x]
    data.x = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [y]
    data.y = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [z]
    data.z = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [ox]
    data.ox = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [oy]
    data.oy = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [oz]
    data.oz = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [ow]
    data.ow = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 56;
  }

  static datatype() {
    // Returns string type for a message object
    return 'dyplom/goalGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '92f979e6d381e46ba6174ad0f4e06da2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    float64 x
    float64 y
    float64 z
    float64 ox
    float64 oy
    float64 oz
    float64 ow
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new goalGoal(null);
    if (msg.x !== undefined) {
      resolved.x = msg.x;
    }
    else {
      resolved.x = 0.0
    }

    if (msg.y !== undefined) {
      resolved.y = msg.y;
    }
    else {
      resolved.y = 0.0
    }

    if (msg.z !== undefined) {
      resolved.z = msg.z;
    }
    else {
      resolved.z = 0.0
    }

    if (msg.ox !== undefined) {
      resolved.ox = msg.ox;
    }
    else {
      resolved.ox = 0.0
    }

    if (msg.oy !== undefined) {
      resolved.oy = msg.oy;
    }
    else {
      resolved.oy = 0.0
    }

    if (msg.oz !== undefined) {
      resolved.oz = msg.oz;
    }
    else {
      resolved.oz = 0.0
    }

    if (msg.ow !== undefined) {
      resolved.ow = msg.ow;
    }
    else {
      resolved.ow = 0.0
    }

    return resolved;
    }
};

module.exports = goalGoal;
