// Auto-generated. Do not edit!

// (in-package dyplom.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class goalFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.a = null;
      this.b = null;
      this.c = null;
      this.oa = null;
      this.ob = null;
      this.oc = null;
      this.od = null;
    }
    else {
      if (initObj.hasOwnProperty('a')) {
        this.a = initObj.a
      }
      else {
        this.a = 0.0;
      }
      if (initObj.hasOwnProperty('b')) {
        this.b = initObj.b
      }
      else {
        this.b = 0.0;
      }
      if (initObj.hasOwnProperty('c')) {
        this.c = initObj.c
      }
      else {
        this.c = 0.0;
      }
      if (initObj.hasOwnProperty('oa')) {
        this.oa = initObj.oa
      }
      else {
        this.oa = 0.0;
      }
      if (initObj.hasOwnProperty('ob')) {
        this.ob = initObj.ob
      }
      else {
        this.ob = 0.0;
      }
      if (initObj.hasOwnProperty('oc')) {
        this.oc = initObj.oc
      }
      else {
        this.oc = 0.0;
      }
      if (initObj.hasOwnProperty('od')) {
        this.od = initObj.od
      }
      else {
        this.od = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type goalFeedback
    // Serialize message field [a]
    bufferOffset = _serializer.float64(obj.a, buffer, bufferOffset);
    // Serialize message field [b]
    bufferOffset = _serializer.float64(obj.b, buffer, bufferOffset);
    // Serialize message field [c]
    bufferOffset = _serializer.float64(obj.c, buffer, bufferOffset);
    // Serialize message field [oa]
    bufferOffset = _serializer.float64(obj.oa, buffer, bufferOffset);
    // Serialize message field [ob]
    bufferOffset = _serializer.float64(obj.ob, buffer, bufferOffset);
    // Serialize message field [oc]
    bufferOffset = _serializer.float64(obj.oc, buffer, bufferOffset);
    // Serialize message field [od]
    bufferOffset = _serializer.float64(obj.od, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type goalFeedback
    let len;
    let data = new goalFeedback(null);
    // Deserialize message field [a]
    data.a = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [b]
    data.b = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [c]
    data.c = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [oa]
    data.oa = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [ob]
    data.ob = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [oc]
    data.oc = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [od]
    data.od = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 56;
  }

  static datatype() {
    // Returns string type for a message object
    return 'dyplom/goalFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '33a401a71705fa7d50b405261e800c87';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    float64 a
    float64 b
    float64 c
    float64 oa
    float64 ob
    float64 oc
    float64 od
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new goalFeedback(null);
    if (msg.a !== undefined) {
      resolved.a = msg.a;
    }
    else {
      resolved.a = 0.0
    }

    if (msg.b !== undefined) {
      resolved.b = msg.b;
    }
    else {
      resolved.b = 0.0
    }

    if (msg.c !== undefined) {
      resolved.c = msg.c;
    }
    else {
      resolved.c = 0.0
    }

    if (msg.oa !== undefined) {
      resolved.oa = msg.oa;
    }
    else {
      resolved.oa = 0.0
    }

    if (msg.ob !== undefined) {
      resolved.ob = msg.ob;
    }
    else {
      resolved.ob = 0.0
    }

    if (msg.oc !== undefined) {
      resolved.oc = msg.oc;
    }
    else {
      resolved.oc = 0.0
    }

    if (msg.od !== undefined) {
      resolved.od = msg.od;
    }
    else {
      resolved.od = 0.0
    }

    return resolved;
    }
};

module.exports = goalFeedback;
